<a href="https://colab.research.google.com/github/sanchita-star/Chat-A-App/blob/master/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim) #dimension
print(arr.shape) #rows and columns
print(arr.size) #ele num
print(arr.dtype) # data types

2
(2, 3)
6
int64


In [6]:
#indexing and slicing
#1D indexing
arr=np.array([10,20,30,40])
print(arr[2])
#2D indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

30
6


In [8]:
#slicing
b=np.array([10,20,30,40,50])
print(b[2:4])

[30 40]


In [12]:
#operation
ar=np.array([10,20,30,40,50])
print(ar[1] * 10 *ar[3])
print(ar[3] +3% ar[4])

8000
43


In [17]:
#for 1D array
a1=np.array([1,2])
a2=np.array([3,4])
a=np.concatenate([a1,a2])
print(a)
#for 2D array
b=np.array([[1,2]])
c=np.array([[3,4]])
print(np.concatenate((b,c),axis=0)) #rowwise
print(np.concatenate((b,c),axis=1))

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 3 4]]


In [26]:
#reshaping array
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(1,2))

ValueError: cannot reshape array of size 6 into shape (1,2)

In [25]:
#splitting arrays
arr=np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]
